server:
  port: 8084
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/sso_user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  mybatis:
    mapperLocations: classpath:mapper/*.xml
    config-location: classpath:mybatis-config.xml
    typeAliasesPackage: com.chason.order.domain
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/