server:
  port: 8083
spring:
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 1d
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/my_order?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 20000  # 连接超时时间（毫秒）不能写0，否则数据会进入redis，但是程序报错
    jedis:
      pool:
        max-idle: 20
        max-wait: -1
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.chason.order.domain
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/
logging:
  level.*: debug